baseURL = "https://lowtech.io/"
languageCode = "en-us"
title = "lowtech.io"
theme = "beautifulhugo"

[Taxonomies]
  tag = "tags"

[Params]
  commit = false
  rss = false
  comments = false
  readingTime = false
  useHLJS = false
  socialShare = false
  showRelatedPosts = true

[[menu.main]]
  name = "#lowtech"
  url = ""
  weight = 1

[[menu.main]]
  name = "Code of Conduct"
  url = "code_of_conduct"
  weight = 10

[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 20
